export const SLICE_NAME = 'app';

export const FETCH_FACTIONS_FAILURE = `${SLICE_NAME}/FETCH_FACTIONS_FAILURE`;
export const FETCH_FACTIONS_SUCCESS = `${SLICE_NAME}/FETCH_FACTIONS_SUCCESS`;
export const FETCH_SOLAR_SYSTEM_FAILURE = `${SLICE_NAME}/FETCH_SOLAR_SYSTEM_FAILURE`;
export const FETCH_SOLAR_SYSTEM_SUCCESS = `${SLICE_NAME}/FETCH_SOLAR_SYSTEM_SUCCESS`;
export const SHOW_LOADER = `${SLICE_NAME}/SHOW_LOADER`;
export const HIDE_LOADER = `${SLICE_NAME}/HIDE_LOADER`;
