export const SLICE_NAME = 'app';

export const FETCH_FACTIONS_FAILURE = `${SLICE_NAME}/FETCH_FACTIONS_FAILURE`;
export const FETCH_FACTIONS_SUCCESS = `${SLICE_NAME}/FETCH_FACTIONS_SUCCESS`;
export const FETCH_SOLAR_SYSTEM_FAILURE = `${SLICE_NAME}/FETCH_SOLAR_SYSTEM_FAILURE`;
export const FETCH_SOLAR_SYSTEM_SUCCESS = `${SLICE_NAME}/FETCH_SOLAR_SYSTEM_SUCCESS`;
export const FETCH_CORPORATION_FAILURE = `${SLICE_NAME}/FETCH_CORPORATION_FAILURE`;
export const FETCH_CORPORATION_SUCCESS = `${SLICE_NAME}/FETCH_CORPORATION_SUCCESS`;
export const FETCH_CEO_FAILURE = `${SLICE_NAME}/FETCH_CEO_FAILURE`;
export const FETCH_CEO_SUCCESS = `${SLICE_NAME}/FETCH_CEO_SUCCESS`;
export const FETCH_RACES_FAILURE = `${SLICE_NAME}/FETCH_RACES_FAILURE`;
export const FETCH_RACES_SUCCESS = `${SLICE_NAME}/FETCH_RACES_SUCCESS`;
export const FETCH_SEARCH_FAILURE = `${SLICE_NAME}/FETCH_SEARCH_FAILURE`;
export const FETCH_SEARCH_SUCCESS = `${SLICE_NAME}/FETCH_SEARCH_SUCCESS`;
export const SHOW_LOADER = `${SLICE_NAME}/SHOW_LOADER`;
export const HIDE_LOADER = `${SLICE_NAME}/HIDE_LOADER`;
